// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArYel1YuJ2m56Ye3WldgOmAJ5jKXXmK8o',
    appId: '1:79032418859:web:3ba50da288586e55e2a06e',
    messagingSenderId: '79032418859',
    projectId: 'finalexam-7d8b5',
    authDomain: 'finalexam-7d8b5.firebaseapp.com',
    storageBucket: 'finalexam-7d8b5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCop8niAvIiJVgT1d0NuVrSoM8ZwpkmTBg',
    appId: '1:79032418859:android:69d4108f63894b3ce2a06e',
    messagingSenderId: '79032418859',
    projectId: 'finalexam-7d8b5',
    storageBucket: 'finalexam-7d8b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr_wVr3f7vnE4a2yKoKqvgfQEZJOsn5aE',
    appId: '1:79032418859:ios:ceef922492d01ec6e2a06e',
    messagingSenderId: '79032418859',
    projectId: 'finalexam-7d8b5',
    storageBucket: 'finalexam-7d8b5.appspot.com',
    iosClientId: '79032418859-f24sjnn2ask5ve0k9itgo528noqpear9.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr_wVr3f7vnE4a2yKoKqvgfQEZJOsn5aE',
    appId: '1:79032418859:ios:ceef922492d01ec6e2a06e',
    messagingSenderId: '79032418859',
    projectId: 'finalexam-7d8b5',
    storageBucket: 'finalexam-7d8b5.appspot.com',
    iosClientId: '79032418859-f24sjnn2ask5ve0k9itgo528noqpear9.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalExam',
  );
}
